apiVersion: v1
kind: Service
metadata:
  name: static-website-service
spec:
  type: NodePort
  selector:
    app: static-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000 # Optional: You can specify the nodePort, or let Kubernetes assign one automatically
